### ISSUE TITLE
no source file in pypi

### ISSUE THREAD

**Issue by harangju** [skojaku/core-periphery-detection#18]
There are no source files in PyPI for versions >=0.0.16.

I think that is why when I `pip install cpnet` and `import cpnet`, I get `ModuleNotFoundError: No module named 'cpnet'`.

Additionally, if I `ls /Users/me/opt/miniconda3/envs/test/lib/python3.7/site-packages/`, I see `cpnet-0.0.18.dist-info` but not `cpnet`, which seems to reflect that there are no source files in PyPI but just the `wheel` file.

https://pypi.org/project/cpnet/0.0.18/#files

**Comment by skojaku** [comment]
Thanks for kindly reporting this. I overlooked this problem! I fixed the issue and the package will be installable shortly. The new version is 0.0.20.  Thanks!

**Comment by harangju** [comment]
Thanks! And thanks for the great package!

**Comment by skojaku** [comment]
I appreciate your feeback! Thanks!
