### ISSUE TITLE
Different resu

### ISSUE THREAD

**Issue by yengogo** [skojaku/core-periphery-detection#20]
Sorry for my title, it was a mistake. The correct one is 'Different results from different tries'

Hello, @skojaku , 
Could I ask why  I receive the different core/periphery results when I try more than once?(same network)🤔
Or is there way to know which result is close to the correct answer? Thank you.

**Comment by skojaku** [comment]
Some algorithms are stochastic algorithms, which means that the results can be different depending on the state of random variable generators. I'll close for now, but please let me know if anything to concern regarding the stochasticitiy.
